[package]
name = "hello-example"
version = "0.1.0"
edition = "2024"

[dependencies]
scars = { path = "../../../scars", optional = true }

[features]
default = ["khal-sim"]
khal-sim = ["scars/khal-sim"]