[package]
name = "scars-khal-e310x"
version = "0.1.0"
authors = ["Tero Huttunen <tero.huttunen@ultic.io>"]
edition = "2024"
build = "build.rs"
license = "MIT/Apache-2.0"
repository = "https://github.com/terohuttunen/scars/"

[lib]
bench = false
doctest = false
test = false

[dependencies]
defmt = "1.0.1"
defmt-semihosting = "0.3.0"
riscv = { version = "0.10.1"}
scars-khal = { path = "../../scars-khal" }
scars-arch-riscv = { path = "../../scars-arch-riscv" }
e310x = {version = "0.11.0"}
static_cell = "2.1.0"
const_env = "0.1.2"
critical-section = { version = "1.1.1" }
portable-atomic = { version = "1", default-features = false, features = ["critical-section"] }
semihosting = { version = "0.1.4", features = ["stdio"], optional = true }

[dev-dependencies]
semihosting = { version = "0.1.4", features = ["stdio"] }

[features]
semihosting = ["dep:semihosting"]
