[package]
name = "scars-fault"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = { version = "1.0.1", optional = true }
scars-fault-macros = { version = "0.1.0", path = "../scars-fault-macros", default-features = false }

[features]
defmt = ["dep:defmt", "scars-fault-macros/defmt"]
display = ["scars-fault-macros/display"]
