[package]
name = "scars-khal-test"
version = "0.1.0"
edition = "2024"
authors = ["Tero Huttunen <tero.huttunen@ultic.io>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/terohuttunen/scars/"

[lib]
test = false

[dependencies]
scars-khal = { version = "0.1.0", path = "../../scars-khal" }
scars-fault = { path = "../../scars-fault", features = ["display"] }
